#!/usr/bin/env python3
"""Link cats/*.gif into the firmware image.

Runs as a PlatformIO `pre:` extra script on every build (see platformio.ini)
and writes src/cats_embed.gen.cpp: one `.incbin` per GIF into .rodata plus the
EMBEDDED_CATS table declared in src/cats_embed.h. The file is rewritten only
when its content changes, and the content carries a hash of every GIF, so
editing, adding or removing a GIF rebuilds and an untouched folder doesn't.

Can also be run by hand to see what would be embedded:  python3 tools/embed_cats.py
"""
import glob
import hashlib
import os
import sys

try:
    Import("env")  # noqa: F821  (SCons injects this)
    ROOT = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CATS_DIR = os.path.join(ROOT, "cats")
OUT = os.path.join(ROOT, "src", "cats_embed.gen.cpp")
MAX_TOTAL = 4 * 1024 * 1024   # the app slot is 6.25MB; keep the GIFs well inside it


def fail(msg):
    print(f"embed_cats: {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    files = sorted(f for f in glob.glob(os.path.join(CATS_DIR, "*.gif"))
                   if not os.path.basename(f).startswith("."))
    if not files:
        fail(f"no GIFs in {CATS_DIR} -- the cat pages need at least one")
    sizes = [os.path.getsize(f) for f in files]
    total = sum(sizes)
    if total > MAX_TOTAL:
        fail(f"{len(files)} GIFs are {total / 1048576:.1f}MB, over the {MAX_TOTAL // 1048576}MB budget")
    if 0 in sizes:
        fail("empty GIF: " + files[sizes.index(0)])

    digest = hashlib.sha1()
    for f in files:
        with open(f, "rb") as fh:
            digest.update(os.path.basename(f).encode() + b"\0" + fh.read())

    lines = [
        "// GENERATED by tools/embed_cats.py from cats/*.gif -- do not edit, do not commit.",
        f"// {len(files)} GIFs, {total} bytes, sha1 {digest.hexdigest()}",
        '#include "cats_embed.h"',
        "",
    ]
    asm = ['  ".pushsection .rodata.cats,\\"a\\"\\n"']
    for i, f in enumerate(files):
        path = f.replace("\\", "\\\\").replace('"', '\\"')
        asm.append(f'  ".balign 4\\n"')
        asm.append(f'  ".global cat_gif_{i}\\n"')
        asm.append(f'  "cat_gif_{i}:\\n"')
        asm.append(f'  ".incbin \\"{path}\\"\\n"')
    asm.append('  ".popsection\\n"')
    lines.append("__asm__(")
    lines.extend(asm)
    lines.append(");")
    lines.append("")
    lines.append('extern "C" {')
    lines.extend(f"extern const uint8_t cat_gif_{i}[];" for i in range(len(files)))
    lines.append("}")
    lines.append("")
    lines.append("const EmbeddedCat EMBEDDED_CATS[] = {")
    for i, (f, s) in enumerate(zip(files, sizes)):
        lines.append(f'  {{ cat_gif_{i}, {s}u, "{os.path.basename(f)}" }},')
    lines.append("};")
    lines.append(f"const int EMBEDDED_CAT_COUNT = {len(files)};")
    text = "\n".join(lines) + "\n"

    try:
        with open(OUT) as fh:
            if fh.read() == text:
                print(f"embed_cats: {len(files)} GIFs, {total / 1024:.0f}KB (unchanged)")
                return
    except FileNotFoundError:
        pass
    with open(OUT, "w") as fh:
        fh.write(text)
    print(f"embed_cats: {len(files)} GIFs, {total / 1024:.0f}KB -> src/cats_embed.gen.cpp")


main()
