#!/usr/bin/env python3
"""Render the dashboard's anti-aliased fonts into VLW for the firmware and a
glyph atlas for simulator-s3.html.

Both outputs come from ONE rendering pass, so the simulator draws the exact
same 8-bit glyph bitmaps, advances and baselines the board does. That is the
S3 port's version of the CYD simulator's "6px per character" rule: text widths
and line breaks in the sim are the firmware's, not the browser's.

    python3 tools/make_vlw.py            # writes src/fonts/fonts_data.h + sim/fonts.js

Only printable ASCII (0x20-0x7E) is generated: the server's sanitize_note()
already folds everything else to '?', and every other string on the board is
firmware-authored ASCII. Digits use Inter's tabular figures (OpenType tnum)
so numbers that tick (clock, countdowns, percentages) don't jitter sideways.

VLW layout (big-endian int32 throughout), as LovyanGFX's VLWfont::loadFont
reads it: 6-word header {glyphCount, version=11, size, 0, ascent, descent},
then 7 words per glyph {unicode, height, width, xAdvance, dY, dX, 0}, sorted
by code point, then every glyph's width*height alpha bytes in the same order.
"""
import argparse
import base64
import json
import os
import struct
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INTER = os.path.expanduser("~/Library/Fonts/Inter-VariableFont_slnt,wght.ttf")
MONO = os.path.expanduser("~/Library/Fonts/GoogleSansCode-VariableFont_MONO,wght.ttf")

# (id, ttf, pixel size, weight). The id is the C enum suffix (FONT_<id>) and
# the simulator's FONTS key. Keep this list, fonts.h's FontId enum and the
# simulator's usage in step -- the generated header carries the enum itself.
FONTS = [
    ("SM",    INTER, 13, 500),   # small labels / footer / captions (CYD size 1)
    ("SMB",   INTER, 13, 650),   # small uppercase card labels
    ("MD",    INTER, 17, 500),   # body text (CYD size 2)
    ("MDB",   INTER, 17, 650),   # emphasised body
    ("LG",    INTER, 26, 650),   # big percentages / headings (CYD size 3)
    ("XL",    INTER, 40, 650),   # digital clock, weather hero temp (CYD size 5)
    ("MONO1", MONO,  11, 450),   # note pane, size 1
    ("MONO2", MONO,  16, 450),   # note pane, size 2
    ("MONO3", MONO,  22, 450),   # note pane, size 3
]

FIRST, LAST = 0x20, 0x7E


def load(path, size, weight):
    f = ImageFont.truetype(path, size, layout_engine=ImageFont.Layout.RAQM)
    axes = f.get_variation_axes()
    vals = []
    for a in axes:
        name = a["name"].decode() if isinstance(a["name"], bytes) else a["name"]
        if name == "Weight":
            vals.append(weight)
        elif name == "Monospaced":
            vals.append(1)
        else:
            vals.append(a["default"])
    f.set_variation_by_axes(vals)
    return f


def render_font(fid, path, size, weight):
    f = load(path, size, weight)
    ascent, descent = f.getmetrics()
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = int(round(f.getlength(ch, features=["tnum"])))
        if code == 0x20:
            glyphs.append(dict(code=code, w=0, h=0, adv=adv, dy=0, dx=0, px=b""))
            continue
        l, t, r, b = f.getbbox(ch, anchor="ls", features=["tnum"])
        w, h = max(r - l, 0), max(b - t, 0)
        img = Image.new("L", (max(w, 1), max(h, 1)), 0)
        ImageDraw.Draw(img).text((-l, -t), ch, font=f, fill=255, anchor="ls", features=["tnum"])
        # dX is clamped to >= 0: LovyanGFX shifts a whole string right when its
        # FIRST glyph has a negative left extent (draw_string's sumX), which the
        # simulator would otherwise have to special-case. Costs a 1px nudge on
        # the odd descender ('j') and removes that parity trap entirely.
        glyphs.append(dict(code=code, w=w, h=h, adv=adv, dy=-t, dx=max(l, 0), px=img.tobytes()[: w * h]))

    # Same maxAscent/maxDescent derivation as VLWfont::loadFont(): start from
    # the header values, raise to the tallest printable glyph (space excluded).
    max_a, max_d = ascent, descent
    for g in glyphs:
        if g["code"] > 0x20:
            max_a = max(max_a, g["dy"])
            max_d = max(max_d, g["h"] - g["dy"])

    vlw = bytearray(struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent))
    for g in glyphs:
        vlw += struct.pack(">7i", g["code"], g["h"], g["w"], g["adv"], g["dy"], g["dx"], 0)
    for g in glyphs:
        vlw += g["px"]
    return dict(id=fid, vlw=bytes(vlw), glyphs=glyphs, max_a=max_a, max_d=max_d)


def write_header(fonts, out):
    lines = [
        "// GENERATED by tools/make_vlw.py -- do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "enum FontId {",
    ]
    lines += [f"  FONT_{f['id']}," for f in fonts]
    lines += ["  FONT_COUNT", "};", ""]
    for f in fonts:
        data = f["vlw"]
        lines.append(f"static const uint8_t FONT_VLW_{f['id']}[{len(data)}] = {{")
        for i in range(0, len(data), 24):
            lines.append("  " + ",".join(str(b) for b in data[i:i + 24]) + ",")
        lines.append("};")
    lines.append("")
    lines.append("static const uint8_t* const FONT_VLW[FONT_COUNT] = {")
    lines += [f"  FONT_VLW_{f['id']}," for f in fonts]
    lines.append("};")
    # Per-glyph advance for 0x20..0x7E, and each font's line metrics. fonts.cpp
    # measures text from these tables (not LovyanGFX's textWidth()) so the
    # simulator can apply the identical sum-of-advances rule.
    lines.append(f"static const uint8_t FONT_ADV[FONT_COUNT][{LAST - FIRST + 1}] = {{")
    for f in fonts:
        lines.append("  {" + ",".join(str(g["adv"]) for g in f["glyphs"]) + "},")
    lines.append("};")
    lines.append("// {maxAscent, lineHeight (= maxAscent + maxDescent)}")
    lines.append("static const uint8_t FONT_METRIC[FONT_COUNT][2] = {")
    for f in fonts:
        lines.append(f"  {{{f['max_a']}, {f['max_a'] + f['max_d']}}},  // {f['id']}")
    lines.append("};")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def write_sim(fonts, out):
    atlas = {}
    for f in fonts:
        atlas[f["id"]] = {
            "maxAscent": f["max_a"],
            "lineHeight": f["max_a"] + f["max_d"],
            # [code, w, h, adv, dY, dX, base64 alpha]
            "glyphs": [[g["code"], g["w"], g["h"], g["adv"], g["dy"], g["dx"],
                        base64.b64encode(g["px"]).decode()] for g in f["glyphs"]],
        }
    with open(out, "w") as fh:
        fh.write("// GENERATED by tools/make_vlw.py -- do not edit by hand.\n")
        fh.write("// Glyph atlas identical to the firmware's VLW fonts (src/fonts/fonts_data.h).\n")
        fh.write("window.S3_FONTS = " + json.dumps(atlas, separators=(",", ":")) + ";\n")


def main():
    ap = argparse.ArgumentParser(description="Generate VLW fonts + simulator glyph atlas.")
    ap.add_argument("--header", default=os.path.join(ROOT, "src", "fonts", "fonts_data.h"))
    ap.add_argument("--sim", default=os.path.join(ROOT, "sim", "fonts.js"))
    args = ap.parse_args()
    for p in (INTER, MONO):
        if not os.path.exists(p):
            print(f"Error: font not found: {p}")
            sys.exit(1)
    fonts = [render_font(*spec) for spec in FONTS]
    os.makedirs(os.path.dirname(args.header), exist_ok=True)
    os.makedirs(os.path.dirname(args.sim), exist_ok=True)
    write_header(fonts, args.header)
    write_sim(fonts, args.sim)
    total = sum(len(f["vlw"]) for f in fonts)
    for f in fonts:
        print(f"  {f['id']:6s} {len(f['vlw']):6d} B  lineH={f['max_a'] + f['max_d']}  "
              f"'0'adv={f['glyphs'][0x30 - FIRST]['adv']}")
    print(f"wrote {args.header} ({total} B of VLW) and {args.sim}")


if __name__ == "__main__":
    main()
