#pragma once

// Anti-aliased text for every page. The fonts are VLW files generated by
// tools/make_vlw.py (Inter + Google Sans Code), preloaded once into
// LovyanGFX VLWfont objects so switching fonts per string costs nothing.
//
// PARITY: text is positioned by its TOP-LEFT (y = top of the line box, glyph
// top lands at y + maxAscent - dY) and measured as the plain sum of per-glyph
// advances from FONT_ADV. simulator-s3.html's gfx.drawText/textW implement the
// exact same two rules over the same generated glyph atlas (sim/fonts.js) --
// change one and you must change the other.
#include <Arduino.h>
#include "fonts/fonts_data.h"

void fontsBegin();

int textW(FontId f, const char* s);
inline int textW(FontId f, const String& s) { return textW(f, s.c_str()); }
int fontLineH(FontId f);     // line box height (maxAscent + maxDescent)
int fontAscent(FontId f);    // baseline offset from the line top

// Draw on `g` (the frame sprite). Returns the x just past the text, so runs
// of differently coloured text can be chained.
int drawText(FontId f, int x, int y, const char* s, uint16_t color);
inline int drawText(FontId f, int x, int y, const String& s, uint16_t color) {
  return drawText(f, x, y, s.c_str(), color);
}
// Right-aligned (text ends at xRight) and centred (on cx) variants.
int drawTextR(FontId f, int xRight, int y, const char* s, uint16_t color);
inline int drawTextR(FontId f, int xRight, int y, const String& s, uint16_t color) {
  return drawTextR(f, xRight, y, s.c_str(), color);
}
int drawTextC(FontId f, int cx, int y, const char* s, uint16_t color);
inline int drawTextC(FontId f, int cx, int y, const String& s, uint16_t color) {
  return drawTextC(f, cx, y, s.c_str(), color);
}
// Draw one character (the note pane's per-glyph colouring walk).
void drawChar(FontId f, int x, int y, char c, uint16_t color);
